version: '3.2'
services:
  postgres:
    image: postgres
    networks:
      - project
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql-init-local.sql:/docker-entrypoint-initdb.d/postgresql-init-local.sql
  storage-server:
    image: domoskanonos/storage-server
    networks:
      - project
    ports:
      - "8094:8080"
    environment:
      JAVA_TOOL_OPTIONS: -Dstorage.path=/app/storage-server -Dspring.datasource.username=${POSTGRES_USER} -Dspring.datasource.password=${POSTGRES_PASSWORD} -Dspring.datasource.url=jdbc:h2:mem:${POSTGRES_DB} -Dserver.port=8080
  crudyboy:
    image: domoskanonos/crudyboy:1.0.3
    networks:
      - project
    ports:
      - "8095:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      PORT: 8080
      CUSTOM_CSS: .customCss {}
      CUSTOM_CSS_URL: https://myserver/my-custom.css
      REQUEST_HEADER_ACCESS_CONTROL_ALLOW_ORIGIN: "*"
      REQUEST_HEADER_ACCESS_CONTROL_ALLOW_METHODS: "GET, POST, OPTIONS, PUT, PATCH, DELETE"
      REQUEST_HEADER_ACCESS_CONTROL_ALLOW_HEADERS: "X-Requested-With,content-type"
      REQUEST_HEADER_ACCESS_CONTROL_ALLOW_CREDENTIALS: "true"
networks:
  project: 
    driver: bridge
