version: '3.2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "/_store/docker/postgresql:/var/lib/postgresql"
  storage-server:
    image: domoskanonos/storage-server
    ports:
      - "8095:8080"
    volumes:
      - "/_store/storage-server:/app"
    environment:
      JAVA_TOOL_OPTIONS: -Dspring.datasource.username=${POSTGRES_USER} -Dspring.datasource.password=${POSTGRES_PASSWORD} -Dstorage.path=/app/storage-server -Dserver.port=8080