version: "3.2"
services:
  web:
    container_name: web
    image: nginx
    networks:
      - devbox
    volumes:
      - /_store/nginx/html:/usr/share/nginx/html
      - /_store/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      #- NGINX_HOST=localhost
      - NGINX_PORT=80
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    networks:
      - devbox
    ports:
      - "3000:3000"
    environment:
      - PGRST_DB_URI=${PGRST_DB_URI}
      - PGRST_JWT_SECRET=${JWT_SECRET}
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=web_anonym
networks:
  devbox:
    driver: bridge